### ISSUE TITLE
Leaking file resources

### ISSUE THREAD

**Issue by DalaraAFL** [TheWicklowWolf/LidaTube#31]
After around 4000 something files downloaded on unraid, i start getting an issue "oserror errno no file descriptors available" I beleive there are some file handles being leaked on each track download.

**Comment by DalaraAFL** [comment]
So Ive stopped running into the issue once ive copied a cookies.txt file in, to avoid the issue with youtube asking you to sign in. (at 6000 or so files currently)

Its possible the resource is being leaked when it fails to download due to that error.

I dont have the full message anymore, but the main segment was "OSError: [Errno 24] No file descriptors available" if i run into it again ill update this issue with the full text.

**Comment by TheWicklowWolf** [comment]
I recommend processing them in smaller batches to prevent rate limiting, import issues, etc.  


> issue with youtube asking you to sign in

This likely indicates a rate limiting problem. I’ll close this for now since the tool isn’t really designed for that scale of imports at once. However, feel free to post the full error message if you encounter it again.
